In do_init(), check that pgdata is set.
So that a better error message can be output.

* Existing message *
pg_rman: could not open file "(null)/global/pg_control"

* A better one *
ERROR: required parameter not specified: PGDATA (-D, --pgdata)